apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django
spec:
  type: NodePort
  selector:
    app: django-todo
  ports:
    - port: 80 #Service port that binds external and container port
      targetPort: 8000 #Port on which cotainer application is running
      nodePort: 30001 #External Port mapped to service pport which is 80 and service port 80 is mapped to targetPort 8000
